
== The event loop

As already stated in the <<_overview,Overview>>, LunaSDL has an event loop that
waits for stimuli such as the expiries of timers, or file descriptor objects that
have become ready for I/O operation, and that dispatches signals sent by agents
or generated by timers.

The event loop relies on a *poll function* that it uses to poll file descriptor
objects for readiness and to get the timing for timers. 
By default, this function is https://github.com/diegonehab/luasocket[LuaSocket]'s
_select_, and the *file descriptor objects* that LunaSDL supports are LuaSocket's
sockets (and compatible objects). This can be changed in the optional configuration
phase by means of the <<sdl.pollfuncs,_sdl.pollfuncs_>> function.

Agents may create and use file descriptor objects with the API provided by LuaSocket
or by alternative modules, and register them in the event loop together with callbacks
to be invoked whenever they are ready for I/O operations.

LunaSDL is fairly agnostic with respect to what a 'file descriptor object' is: it
only expects it to be compatible with the _poll function_, and to support a couple
of methods: a _settimeout_ method which LunaSDL calls with a _0_ timeout argument
to force the object to be non-blocking, and a _$$__tostring$$_ metamethod (for traces). 

Multiple file descriptor objects can be used concurrently, with the only requirement
that they must not be blocking, otherwise they would block the timers and the
dispatching of signals (LunaSDL forces the file descriptors timeout to _0_ when they
are registered, and this should not be changed by the agent scripts).

=== Registering file descriptors

Registration and deregistration of file descriptor objects in the event loop is done 
with the following two functions:

'''
[[sdl.register]]
* *sdl.register* ( _object_, _readcallback_ [, _writecallback_ ]) +
 +
Registers a file descriptor object in the event loop. The _object_ argument must be
compatible with the <<sdl.pollfuncs,_poll functiont_>> used by LunaSDL 
(e.g., if the default configuration is used, then _object_ must be a LuaSocket socket or 
a compatible object). +
 +
If _readcallback_ is not _nil_, then the event loop invokes `readcallback(object)`
whenever it detects that _object_ is ready for read operations. Similarly,
if _writecallback_ is not _nil_, then the event loop invokes `writecallback(object)`
whenever it detects that _object_ is ready for write operations. +
 +
Callbacks are executed in the environment of the agent that registered the object,
with the same agent set as _current_
(a callback is, de facto, a <<_transitions, transition>> that instead of being triggered
by the arrival of an input signal, it is triggered by the detection of the readiness of
a file descriptor object). +

'''
[[sdl.deregister]]
* *sdl.deregister* ( _object_ [, _mode_ ]) +
 +
Deregisters _object_ from the event loop. The optional _mode_ argument (a string)
specifies if the object must be deregistered for read operations (_"r"_), for
write operations (_"w"_), or for both (_"rw"_ or _"wr"_). If not passed, _mode_ defaults
to _"rw"_. Deregistration of not registered objects do not cause errors.

=== Sockets

If the default _poll function_ (i.e. LuaSocket's _socket.select_) is used, then agents
may create and use sockets with the API provided by LuaSocket, registering them in the
event loop with the <<sdl.register, _sdl.register_>> function.

Notice that the _socket. select_ function supports also custom _file descriptor_
objects (i.e. other than sockets), provided they have a couple of methods needed by
_socket.select_ to deal with them.
For more details, see https://github.com/diegonehab/luasocket[LuaSocket]'s documentation.

=== Event loop details

Roughly speaking, at each round the event loop does the following operations, in the
order they are exposed here:

. First, it waits for stimuli. As already stated, stimuli may be the expiry of timers,
or the readiness of registered file descriptors objects for I/O operations. 
How long the event loop waits, it depends on the presence of signals yet to be dispatched:
if there are any, it just gives a glance for stimuli (i.e. it polls with a
_0_ timeout) and then it goes on to the next point as soon as possible. Otherwise
it waits indefinitely until the next stimulus.
. Then, if any file descriptor object is ready for I/O, it invokes the corresponding callback.
The callback execution may result in the scheduling of signals. Any such signal will
be dispatched later in this same round.
. Then, for any timer that has expired since the previous round, it schedules the
corresponding signal to be delivered to the timer's owner agent. This signal will 
also be dispatched in this same round.
. Finally, it dispatches all signals scheduled until now, in their order of priority.
The dispatching of these signals may again result in the scheduling of new signals, 
but these will be dispatched in the next round (this is to avoid deadlocks).

<<<
