
== Procedures

*SDL procedures* are sub-parts of state machines, that can be reused in
different agent scripts.

A procedure in LunaSDL is implemented as a special kind of agent, created by
means of the <<sdl.procedure,_sdl.procedure_>> function, that replaces its
caller from when it is called until it returns. 
More precisely, a procedure replaces its caller _as destination and source of
signals_, i.e. all the signals addressed to the caller are redirected to the
procedure, which may consume them or <<sdl.save,save>> them, and all the signals 
sent by the procedure are sent on behalf of its caller (in other words, with
the caller's pid as _sender_).

When a procedure returns, all the signal it saved are automatically moved in
its parent's _saved queue_ and the normal addressing  of signals is re-established.

Procedures can be nested, that is, a procedure may call another procedure,
but agents (and procedures) can directly execute only one procedure at a time
because they are replaced by it. Nested procedures all act on behalf of the original
caller, whose pid they find in the *_$$caller_$$_* <<_special_variables, special variable>>.

State machines for procedures are defined in _procedure scripts_ with the same
functions used in regular <<_agent_scripts, agent scripts>>, with the exception
of the <<sdl.stop,_sdl.stop_>> function (procedure scripts shall use the 
<<sdl.procreturn, _sdl.procreturn_>> function instead).

Another difference with regular agents is that procedures may not create timers,
but they can use timers owned by the agent they act on behalf of.

'''
[[sdl.procedure]]
* *sdl.procedure* (_atreturn_, _name_ , _script_, _..._ ) +
-> _pid_ +
 +
Executes (i.e. creates) an SDL procedure as described above.
The _name_, _script_ and _..._ arguments are the same as in the functions that
<<_creating_agents, create regular agents>> 
(the only difference is that if _name=nil_, then the default name _"procedure<pid>"_
is automatically assigned instead of _"agent<pid>"_). +
 +
The _atreturn_ argument defines actions to be executed in the caller agent's environment
when the procedure returns. It may be a function, a string denoting a state, or _nil_
if no actions need to be executed. +
 +
When the procedure returns, if _atreturn_ is a function, it is executed passing it 
as arguments the values returned by the procedure (if any). If _atreturn_ is a string, 
then <<sdl.nextstate, _sdl.nextstate(atreturn)_>> is automatically executed instead.

'''
[[sdl.procreturn]]
* *sdl.procreturn* ( _..._ ) +
 +
Returns from a procedure. This function is to be used in the procedure script 
instead of <<sdl.stop,_sdl.stop_>>, to terminate the procedure and possibly
return values to the parent. +
 +
The arguments passed to _sdl.procreturn_ (if any) are in turn passed to the
_atreturn_ function set by the parent when the procedure was created. +
 +
No script code should follow a call of this function.

<<<
