
== Signals

=== Format of signals

Signals exchanged between agents in LunaSDL, as well as signals generated by 
<<_timers, timers>>, are and must be Lua
http://www.lua.org/manual/5.3/manual.html#3.4.7[*'sequences'*], i.e.
tables whose elements are indexed by integer keys, starting from _1_ to some 
positive integer _n_ (_>=1_), and no gaps in between.

The first element in a signal (the element with numeric key=_1_) must be a
string and denotes the *signal name*. For example:

[source,lua,indent=1]
----
mysignal = { "MYSIGNAL", "hello", 1, 2, 3, self_, true }
-- "MYSIGNAL" is the signal name; the fields values follow
----

LunaSDL makes no other assumptions regarding the format and meaning of signals and
of their fields.

Please note, however, that signals are sent by *shallow-copy*. Thus, if for
example a signal field contains a table, the destination agent receives a reference
to the table, not a copy. Moreover, any element indexed with a non-numeric key is
not copied (i.e. sent) at all.

Signals are sent, saved and re-scheduled using the functions described in the following
subsections.

=== Sending signals

[[sdl.send]]
* *sdl.send* ( _signal_, _dstpid_, [, _priority_ ]) +
-> _now_ +
 +
Sends the SDL _signal_ to the agent identified by _dstpid_, with the specified
_priority_, and returns the current <<_system_time,time>>. +
 +
The _priority_ argument, if present, should be an integer between _1_ (high)
and _N_ (low), where _N_ is the <<sdl.prioritylevels, number of priority levels>>
optionally configured at startup. +
 +
If _priority_ is not specified, or if it is greater than _N_, the signal
is sent without priority (which means lowest). +
 
NOTE: The SDL-experienced reader may have noticed that LunaSDL has _priority
outputs_, while standard SDL has _priority inputs_. The following function somehow
straightens things by allowing the receiver agent to specify the priorities of input
signals, and override the priorities specified by sender agents.

'''
[[sdl.priorityinput]]
* *sdl.priorityinput* ( _signame_, [ _priority_ ] ) +
 +
Configures the _priority_ for input signals named _signame_. +
 +
This function is (optionally) used by an agent to impose priorities for input signals.
If it is called with a non-_nil_ _priority_ argument, then signals named _signame_ sent
to this agent will be sent with the specified _priority_, no matter the priority specified
by the sender. +
 +
If _priority_ is _nil_, the desired priority is reset and the priority specified by the
sender applies. +
 +
The _sdl.priorityinput_ function can be used by an agent at any time, but only signals sent
after it is called are affected by it, i.e. signals already sent but not yet dispatched 
are not affected (so, beware of subtle differences with the standard SDL priority input
construct). +
 +
Signals generated by <<_timers, timers>>, <<_time_triggered_signals,time-triggered signals>>
and <<sdl.restore, re-scheduled signals>> are not affected either.

=== Time-triggered signals

[[sdl.sendat]]
* *sdl.sendat* ( _signal_, _dstpid_, _at_ [, _maxdelay_ ]) +
 +
Schedules the SDL _signal_ to be sent to the agent identified by _dstpid_ at the
point in <<_system_time,time>> specified by _at_. +
 +
The optional _maxdelay_ argument is the maximum delay, in seconds after _at_, after
which the signal must be considered stale, and discarded. A _nil_ value for _maxdelay_
means _infinity_ (i.e. the signal never expires). +
 +
When a signal is sent with this function, LunaSDL retains it in an internal queue
and only when the time specified by the _at_ argument arrives, it sends it to the
destination agent (with maximum priority). 
If, for some reason, the signal can not be delivered before the point in time given by
_at + maxdelay_, LunaSDL silently discards it.

NOTE: This construct is not part of the SDL standard. It is instead inspired
by a proposal contained in the paper "`Real-time signaling in SDL`",
by M. Krämer, T. Braun, D. Christmann and R. Gotzhein, published in _SDL'11
Proceedings of the 15th international conference on Integrating System and
Software Modeling_, Springer-Verlag, 2011.

=== Saving and re-scheduling signals

[[sdl.save]]
* *sdl.save* ( ) +
 +
To be used within <<_agent_scripts,transitions>> triggered by input signals,
saves the current input signal (i.e. the content of the 
*_$$signal_$$_* <<_special_variables, special variable>>) in the agent's _saved queue_, for later
re-scheduling. +
 +
Saved signals are automatically re-scheduled when the agent changes its state
with a <<sdl.nextstate,_sdl.nextstate_>> call, but can be re-scheduled explicitly
at any time by means of the <<sdl.restore,_sdl.restore_>> function described below. +
 +
In both cases, saved signals are re-scheduled without priority (even if they
were originally sent with priority) and in the same order they were saved.

'''
[[sdl.restore]]
* *sdl.restore* ( ) +
 +
Explicitly re-schedules all the signals saved in the agent's _saved queue_.

<<<
