
== Special variables

In LunaSDL applications, identifiers composed of one or more lower-case letters
and ending with an underscore (e.g., _$$self_$$_) are *reserved for special variables*
managed by the LunaSDL module, and should not be used in agents' scripts code.

The special (global) variables listed below are always set, and are properly updated
every time (and before) a transition is executed.

[cols="15,85", options="header"]
|===
|Variable|Description
|*_$$self_$$_* | the <<pid,pid>> of the agent itself.
|*_$$name_$$_* | the name of the agent.
|*_$$block_$$_*| the pid of the SDL block the agent is contained in.
|*_$$parent_$$_*| the pid of the parent agent.
|*_$$offspring_$$_*| the pid of the last child agent created by this one (or _nil_ if none).
|*_$$state_$$_*| the current <<_agent_scripts, state name>> (or _nil_ if the agent is stopping).
|*_$$signal_$$_*| the current input <<_signals, signal>>.
|*_$$signame_$$_*| the name of the input signal (same as _$$signal_[1]$$_ )
|*_$$sender_$$_*| the sender of the input signal (pid, or tid if the signal is timer-generated).
|*_$$caller_$$_*| the pid of the original caller of the <<_procedures, procedure>> (_nil_,
if the current agent is not a procedure).
|*_$$istimer_$$_*| a boolean indicating if the input signal was generated by a <<_timers,timer>>.
|*_$$sendtime_$$_*| a <<_system_time, timestamp>> indicating when the signal was sent.
|*_$$recvtime_$$_*| a timestamp indicating when the signal was received.
|*_$$exptime_$$_*| a timestamp indicating when the signal becomes stale.
|===

All the above variables are to be considered *read-only* (care should be taken not
to change their values from agent script code).

NOTE: The *_$$sendtime_$$_* timestamp refers actually to the point in time the
signal was scheduled for dispatching. If the signal was sent with _sdl.send_, this
corresponds to when the function was called; for timer-generated signals, it is the point
in time the timer expiry was detected; for time-triggered signals it is the point in time
the signal was actually delivered.

<<<
